### PR TITLE
fix: Adjust bullet-heading alignment

### LINKED ISSUE #1: Bullet for H3 headers not aligned
The bullet for H3 header is not center-aligned with the text. Is this by design?

CleanShot 2022-07-28 at 09 17 34

### PR DESCRIPTION
**Pull request by eryc-cc**
Resolves #1

### CODE REVIEW

**Comment by eryc-cc** [comment]
@gavinmn feel free to commit this into another branch (I tried not to fork, but the repo doesn't allow me to push).

**Review by gavinmn — CHANGES_REQUESTED** [review]
I haven't been able to figure out exactly what is causing this, but I'm getting a weird jumping effect when you focus a block underneath a heading. 

https://user-images.githubusercontent.com/59900904/181862386-dc4d2545-cd70-4336-9298-6cbbb358e73b.mp4

**Comment by eryc-cc** [comment]
I think it's because when you focus on the line, it replaces the text tag with a `<textarea>`, and the height is different.

That's the _only_ thing I could find that might justify this. It's a 2 pixel difference. 😖 

https://user-images.githubusercontent.com/101464991/181863883-00c4cc9b-5304-457d-8aa0-5a61ef3e2d3c.mov

**Review by gavinmn — APPROVED** [review]

**Comment by gavinmn** [comment]
@pixelsbyeryc I was able to solve it by removing `:not(.focus-within)`

**Pull request merged**
